<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>BroadChatClientApp</name>
    <message>
        <source>인증 실패</source>
        <translation>Authentication Failed</translation>
    </message>
    <message>
        <source>서버 인증 토큰 불일치. 설정 창에서 토큰을 수정한 뒤 재시도하거나 종료하세요.</source>
        <translation>Server authentication token mismatch. Edit the token in Settings and retry, or quit.</translation>
    </message>
    <message>
        <source>버전 불일치</source>
        <translation>Version Mismatch</translation>
    </message>
    <message>
        <source>서버와 클라이언트 프로토콜 버전이 호환되지 않습니다. 업그레이드가 필요합니다.</source>
        <translation>Server and client protocol versions are incompatible. Upgrade required.</translation>
    </message>
    <message>
        <source>연결 중단</source>
        <translation>Connection Terminated</translation>
    </message>
    <message>
        <source>서버와 연결이 영구 중단되었습니다 (사유: %1).</source>
        <translation>Connection to server permanently terminated (reason: %1).</translation>
    </message>
    <message>
        <source>설정 수정</source>
        <translation>Edit Settings</translation>
    </message>
    <message>
        <source>종료</source>
        <translation>Quit</translation>
    </message>
</context>
<context>
    <name>ClientConfigDialog</name>
    <message>
        <source>(off)</source>
        <translation>(off)</translation>
    </message>
    <message>
        <source>BroadChat Client Settings</source>
        <translation>BroadChat Client Settings</translation>
    </message>
    <message>
        <source>메인 앱 서버 주소 (IP 또는 호스트명)</source>
        <translation>Main app server address (IP or hostname)</translation>
    </message>
    <message>
        <source>메인 앱 서버 TCP 포트</source>
        <translation>Main app server TCP port</translation>
    </message>
    <message>
        <source>(empty = no authentication)</source>
        <translation>(empty = no authentication)</translation>
    </message>
    <message>
        <source>메인 앱에서 생성한 토큰. 빈 값이면 인증 안 함</source>
        <translation>Token generated by the main app. Leave empty to disable authentication.</translation>
    </message>
    <message>
        <source>Show</source>
        <translation>Show</translation>
    </message>
    <message>
        <source>Paste</source>
        <translation>Paste</translation>
    </message>
    <message>
        <source>Clear</source>
        <translation>Clear</translation>
    </message>
    <message>
        <source>Host</source>
        <translation>Host</translation>
    </message>
    <message>
        <source>Port</source>
        <translation>Port</translation>
    </message>
    <message>
        <source>Auth Token</source>
        <translation>Auth Token</translation>
    </message>
    <message>
        <source>Connection</source>
        <translation>Connection</translation>
    </message>
    <message>
        <source>채팅 본문 폰트. 빈 값(system default)은 상단 &apos;System&apos; 선택으로는 반영 안 됨 — 명시 선택 권장</source>
        <translation>Chat body font. Empty (system default) is not applied via the top &apos;System&apos; choice — explicit selection recommended.</translation>
    </message>
    <message>
        <source>Bold</source>
        <translation>Bold</translation>
    </message>
    <message>
        <source>Italic</source>
        <translation>Italic</translation>
    </message>
    <message>
        <source>모델에 보관할 최근 메시지 상한. 초과 시 가장 오래된 메시지 제거</source>
        <translation>Maximum number of recent messages held in the model. Oldest messages are dropped when exceeded.</translation>
    </message>
    <message>
        <source>Font Family</source>
        <translation>Font Family</translation>
    </message>
    <message>
        <source>Font Size</source>
        <translation>Font Size</translation>
    </message>
    <message>
        <source>Style</source>
        <translation>Style</translation>
    </message>
    <message>
        <source>Line Spacing</source>
        <translation>Line Spacing</translation>
    </message>
    <message>
        <source>Max Messages</source>
        <translation>Max Messages</translation>
    </message>
    <message>
        <source>Chat</source>
        <translation>Chat</translation>
    </message>
    <message>
        <source>뷰어 카운트 오버레이 위치. Hidden이면 표시 안 함</source>
        <translation>Viewer count overlay position. &apos;Hidden&apos; disables display.</translation>
    </message>
    <message>
        <source>투명 모드 배경색 (#AARRGGBB). 기본 완전 투명</source>
        <translation>Transparent-mode background color (#AARRGGBB). Default is fully transparent.</translation>
    </message>
    <message>
        <source>불투명 모드 배경색 (#AARRGGBB). 기본 흰색</source>
        <translation>Opaque-mode background color (#AARRGGBB). Default is white.</translation>
    </message>
    <message>
        <source>(empty = use theme)</source>
        <translation>(empty = use theme)</translation>
    </message>
    <message>
        <source>채팅 본문 폰트 색 override. 빈 값 = 테마 기본</source>
        <translation>Chat body font color override. Empty = use theme default.</translation>
    </message>
    <message>
        <source>(empty = no outline)</source>
        <translation>(empty = no outline)</translation>
    </message>
    <message>
        <source>채팅 텍스트 윤곽선 색. 빈 값 = 윤곽선 없음</source>
        <translation>Chat text outline color. Empty = no outline.</translation>
    </message>
    <message>
        <source>방송창 가로 크기. 드래그로 크기 변경 시 자동 갱신</source>
        <translation>Broadcast window width. Auto-updates when you resize the window.</translation>
    </message>
    <message>
        <source>방송창 세로 크기. 드래그로 크기 변경 시 자동 갱신</source>
        <translation>Broadcast window height. Auto-updates when you resize the window.</translation>
    </message>
    <message>
        <source>Window Width</source>
        <translation>Window Width</translation>
    </message>
    <message>
        <source>Window Height</source>
        <translation>Window Height</translation>
    </message>
    <message>
        <source>Viewer Count Position</source>
        <translation>Viewer Count Position</translation>
    </message>
    <message>
        <source>Transparent BG</source>
        <translation>Transparent BG</translation>
    </message>
    <message>
        <source>Opaque BG</source>
        <translation>Opaque BG</translation>
    </message>
    <message>
        <source>Body Font Color</source>
        <translation>Body Font Color</translation>
    </message>
    <message>
        <source>Text Outline Color</source>
        <translation>Text Outline Color</translation>
    </message>
    <message>
        <source>Broadcast</source>
        <translation>Broadcast</translation>
    </message>
    <message>
        <source>Pick color...</source>
        <translation>Pick color...</translation>
    </message>
    <message>
        <source>Clear Token</source>
        <translation>Clear Token</translation>
    </message>
    <message>
        <source>인증 기능을 비활성화합니다. 계속하시겠습니까?</source>
        <translation>This will disable authentication. Continue?</translation>
    </message>
    <message>
        <source>Transparent Mode Background</source>
        <translation>Transparent Mode Background</translation>
    </message>
    <message>
        <source>Opaque Mode Background</source>
        <translation>Opaque Mode Background</translation>
    </message>
    <message>
        <source>Chat Body Font Color</source>
        <translation>Chat Body Font Color</translation>
    </message>
    <message>
        <source>Chat Text Outline Color</source>
        <translation>Chat Text Outline Color</translation>
    </message>
    <message>
        <source>Not set</source>
        <translation>Not set</translation>
    </message>
    <message>
        <source>Transparent Preview</source>
        <translation>Transparent Preview</translation>
    </message>
    <message>
        <source>Opaque Preview</source>
        <translation>Opaque Preview</translation>
    </message>
</context>
<context>
    <name>MainBroadcastWindow</name>
    <message>
        <source>세팅</source>
        <translation>Settings</translation>
    </message>
    <message>
        <source>종료</source>
        <translation>Quit</translation>
    </message>
    <message>
        <source>연결 대기 중</source>
        <translation>Waiting for connection</translation>
    </message>
</context>
<context>
    <name>BroadChatClientApp</name>
    <message>
        <source>연결됨</source>
        <translation>Connected</translation>
    </message>
    <message>
        <source>재연결 중…</source>
        <translation>Reconnecting…</translation>
    </message>
    <message>
        <source>인증 실패 — 설정 확인 필요</source>
        <translation>Authentication failed — check settings</translation>
    </message>
    <message>
        <source>버전 불일치 — 업그레이드 필요</source>
        <translation>Version mismatch — upgrade required</translation>
    </message>
</context>
</TS>
